AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda function for send Email using SES
Parameters:
  Email:
    Description: This email will be register on SES for recive the emails from the app.
    Type: String
    ConstraintDescription: You should enter a valid email
  ArnLambdaRole:
    Description: This ARN is needed for assosiate a role to the Lambda fn for handle the permissions.
    Type: String
  SubjectEmail:
    Description: This is subject show it on the Emails.
    Type: String
Resources:
  LambdaSESEmailHandler:
    Type: AWS::Lambda::Function
    Properties:
      Handler: "index.lambda_handler"
      Code:
        ZipFile:
          Fn::Sub: |
            import boto3, os, json

            FROM_EMAIL_ADDRESS = '${Email}'
            SUBJECT_EMAIL = '${SubjectEmail}'
            ses = boto3.client('ses')

            def lambda_handler(event, context):
                
                # Print event data to logs .. 
                print("Received event: " + json.dumps(event))
                
                # Publish message directly to email, provided by EmailOnly or EmailPar TASK
                ses.send_email( Source=FROM_EMAIL_ADDRESS,
                    Destination={ 'ToAddresses': [ event['Input']['email'] ] }, 
                    Message={ 'Subject': {'Data': SUBJECT_EMAIL},
                        'Body': {'Text': {'Data': event['Input']['message']}}
                    }
                )
                return 'Success!'
      Runtime: python3.9
      Role: !Ref ArnLambdaRole
Outputs:
  ArnLambdaFnSES:
    Description: The value of ARN will be use for the AWS State Machines
    Value: !GetAtt LambdaSESEmailHandler.Arn
