AWSTemplateFormatVersion: "2010-09-09"
Description: Save the URL of API in a Parameter
Parameters:
    ServelessURL:
        Default: Error
        Description: Url of the API Created
        Type: String
Resources:
    SSMParamURL:
        Type: "AWS::SSM::Parameter"
        Description: Url of the API Created
        Properties:
            Name: /Serveless/APIGateway/URL
            Type: String
            Value: !Ref ServelessURL
