AWSTemplateFormatVersion: "2010-09-09"
Description: Creation CodeBuild project for build and store the artifacts in a S3 Bucket

Parameters:
  CodeBuildProjectName:
    Type: String
  CodeCommitRepoCloneHTTP:
    Type: String
  ECRRepoName:
    Type: String
  CodeCommitRepoARN:
    Type: String
  CodeBuildImgCPU:
    Type: String
  LogGroupName:
    Type: String
  LogStreamName:
    Type: String

Resources:
  ArtifactStoreS3Location:
    Type: AWS::S3::Bucket

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref CodeBuildProjectName
      Description: A description about my project
      Source:
        Location: !Ref CodeCommitRepoCloneHTTP
        Type: CODECOMMIT
      ServiceRole: !Ref CodeBuildExecRole
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        PrivilegedMode: true
        Image: !Ref CodeBuildImgCPU
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Type: PLAINTEXT
            Value: !Ref AWS::Region
          - Name: AWS_ACCOUNT_ID
            Type: PLAINTEXT
            Value: !Ref AWS::AccountId
          - Name: IMAGE_TAG
            Type: PLAINTEXT
            Value: latest
          - Name: IMAGE_REPO_NAME
            Type: PLAINTEXT
            Value: !Ref ECRRepoName
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref LogGroupName
          Status: ENABLED
          StreamName: !Ref LogStreamName

  CodeBuildExecRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub codebuild-${CodeBuildProjectName}-build-service-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"

  CodeBuildECRPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: CodeBuildECRPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:CompleteLayerUpload"
              - "ecr:GetAuthorizationToken"
              - "ecr:InitiateLayerUpload"
              - "ecr:PutImage"
              - "ecr:UploadLayerPart"
            Resource: "*"
            Effect: Allow
      Roles:
        - Ref: "CodeBuildExecRole"

  CodeBuildCloudWatchLogsPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: CodeBuildCloudWatchLogsPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource:
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${LogGroupName}"
              - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${LogGroupName}:*"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
      Roles:
        - !Ref CodeBuildExecRole

  CodeBuildBasePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: CodeBuildBasePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource:
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${CodeBuildProjectName}
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${CodeBuildProjectName}:*
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
          - Effect: Allow
            Resource:
              - !Join ["", [!GetAtt ArtifactStoreS3Location.Arn, "*"]]
            Action:
              - "s3:PutObject"
              - "s3:GetObject"
              - "s3:GetObjectVersion"
              - "s3:GetBucketAcl"
              - "s3:GetBucketLocation"
          - Effect: Allow
            Resource:
              - !Ref CodeCommitRepoARN
            Action:
              - "codecommit:GitPull"
          - Effect: Allow
            Action:
              - "codebuild:CreateReportGroup"
              - "codebuild:CreateReport"
              - "codebuild:UpdateReport"
              - "codebuild:BatchPutTestCases"
              - "codebuild:BatchPutCodeCoverages"
            Resource:
              - !Sub arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/${CodeBuildProjectName}-*
      Roles:
        - !Ref CodeBuildExecRole

Outputs:
  S3Arn:
    Value: !GetAtt ArtifactStoreS3Location.Arn
  S3Name:
    Value: !Ref ArtifactStoreS3Location
  CodeBuildNameProject:
    Value: !Ref CodeBuildProject
