AWSTemplateFormatVersion: "2010-09-09"
Description: Creation of a repository on CodeCommit

Parameters:
  RepoName:
    Type: String
  RepoBranchName:
    Type: String
  SourceCodeBucket:
    Type: String
  SourceFilePatch:
    Type: String

Resources:
  MyRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepoName
      Code:
        BranchName: !Ref RepoBranchName
        S3:
          Bucket: !Ref SourceCodeBucket
          Key: !Ref SourceFilePatch

Outputs:
  CodeCommitRepoCloneHTTP:
    Value: !GetAtt MyRepo.CloneUrlHttp
  CodeCommitRepoCloneSSH:
    Value: !GetAtt MyRepo.CloneUrlSsh
  CodeCommitRepoName:
    Value: !GetAtt MyRepo.Name
  CodeCommitRepoARN:
    Value: !GetAtt MyRepo.Arn
