AWSTemplateFormatVersion: "2010-09-09"
Description: Creation of a private repository on ECR

Parameters:
  ECRRepoName:
    Type: String

Resources:
  MyRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ECRRepoName

Outputs:
  ECRRepoURL:
    Value: !GetAtt MyRepository.RepositoryUri
  ECRRepoName:
    Value: !Ref MyRepository
