AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  NameCluster:
    Type: String

Resources:
  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: !Ref NameCluster
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 1
      ClusterSettings:
        - Name: containerInsights
          Value: disabled
      Configuration:
        ExecuteCommandConfiguration:
          Logging: DEFAULT
      ServiceConnectDefaults:
        Namespace: !Ref NameCluster

Outputs:
  ECSClusterARN:
    Value: !GetAtt ECSCluster.Arn
  ECSClusterName:
    Value: !Ref ECSCluster
