AWSTemplateFormatVersion: 2010-09-09
Description: The template used to create an ECS Service.

Parameters:
  ECSServiceName:
    Type: String
  ECSServiceDesiredCount:
    Type: Number
  ECRRepoName:
    Type: String
  ECSClusterARN:
    Type: String
  ECSTaskDefinitionARN:
    Type: String
  SecurityGroupIDs:
    Type: List<AWS::EC2::SecurityGroup::Id>
  VpcID:
    Type: AWS::EC2::VPC::Id
  SubnetIDs:
    Type: List<AWS::EC2::Subnet::Id>
  ARNTargetG:
    Type: String

Resources:
  ECSService:
    Type: "AWS::ECS::Service"
    Properties:
      Cluster: !Ref ECSClusterARN
      TaskDefinition: !Ref ECSTaskDefinitionARN
      LaunchType: FARGATE
      ServiceName: !Ref ECSServiceName
      SchedulingStrategy: REPLICA
      DesiredCount: !Ref ECSServiceDesiredCount
      LoadBalancers:
        - ContainerName: !Ref ECRRepoName
          ContainerPort: 80
          LoadBalancerName: !Ref "AWS::NoValue"
          TargetGroupArn: !Ref ARNTargetG
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups: !Ref SecurityGroupIDs
          Subnets: !Ref SubnetIDs
      PlatformVersion: LATEST
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      DeploymentController:
        Type: ECS
      ServiceConnectConfiguration:
        Enabled: false
      EnableECSManagedTags: true

Outputs:
  ClusterName:
    Description: The cluster used to create the service.
    Value: !Ref ECSClusterARN
  ECSService:
    Description: The created service.
    Value: !Ref ECSService
