AWSTemplateFormatVersion: "2010-09-09"
Description: Create a task definition for a web server.

Parameters:
  ECSTaskDefName:
    Type: String
  ECRRepoURL:
    Type: String
  ECRRepoName:
    Type: String

Resources:
  ECSTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Family: !Ref ECSTaskDefName
      ContainerDefinitions:
        - Name: !Ref ECRRepoName
          Image: !Ref ECRRepoURL
          Essential: true
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
              Protocol: tcp
              AppProtocol: http
      NetworkMode: awsvpc
      RuntimePlatform:
        CpuArchitecture: X86_64
        OperatingSystemFamily: LINUX
      Cpu: 0.5 vCPU
      Memory: 1 GB
      TaskRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole
      ExecutionRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole

Outputs:
  ECSTaskDefinitionARN:
    Value: !Ref ECSTaskDefinition
  ECSTaskDefName:
    Value: !Ref ECSTaskDefName
