AWSTemplateFormatVersion: "2010-09-09"
Description: Creation of a Event Bridge Rule

Parameters:
  AppName:
    Type: String
  PipelineARN:
    Type: String
  CodeCommitRepoARN:
    Type: String

Resources:
  MyNewEventsRule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: "Amazon CloudWatch Events rule to automatically start your pipeline when a change occurs in the AWS CodeCommit source repository and branch. Deleting this may prevent changes from being detected in that pipeline. Read more: http://docs.aws.amazon.com/codepipeline/latest/userguide/pipelines-about-starting.html"
      Name: !Sub codepipeline-${AppName}-master-${AWS::AccountId}-rule
      EventPattern: !Sub |
        {
          "source": ["aws.codecommit"],
          "detail-type": ["CodeCommit Repository State Change"],
          "resources": ["${CodeCommitRepoARN}"],
          "detail": {
            "event": ["referenceCreated", "referenceUpdated"],
            "referenceType": ["branch"],
            "referenceName": ["master"]
          }
        }
      State: ENABLED
      Targets:
        - Arn: !Ref PipelineARN
          Id: Id1234
          RoleArn: !GetAtt CWCodePipelineRole.Arn

  CWCodePipelineRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub cwe-role-${AWS::Region}-${AppName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "events.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"

  CodePipelineExec:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: CodePipelineExec
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "codepipeline:StartPipelineExecution"
            Resource:
              - !Ref PipelineARN
      Roles:
        - !Ref CWCodePipelineRole
