AWSTemplateFormatVersion: "2010-09-09"
Description: This nested stack contain all the resources needed for create a CI/CD from a Repository using containers.

Parameters:
  AppName:
    Type: String
    Default: my-first-pipeline
    Description: Provide a name for your app
  SourceCodeBucket:
    Type: String
    Description: Provide the name of your bucket where is store your initial code
  SourceFilePath:
    Type: String
    Default: app.zip
    Description: Provide the key object or relative path of your zipped code
  RepoName:
    Type: String
    Default: pipeline-cc
    Description: Provide a name for your repository on CodeCommit
  RepoBranchName:
    Type: String
    Default: master
    Description: Provide a name for the master or main branch that will activate the pipeline.
  ECRRepoName:
    Type: String
    Default: pipeline-erc
    Description: Provide a name for your repository on Elastic Container Registry
  NameCluster:
    Type: String
    Default: allthepipeapps
    Description: Provide a name for your ECS Cluster where will be allocated the ECS Services
  ECSTaskDefName:
    Type: String
    Default: pipeline-td
    Description: Provide a name for your ECS Task Definition
  ECSServiceName:
    Type: String
    Default: pipeline-service
    Description: Provide a name for your ECS Service
  ECSServiceDesiredCount:
    Type: Number
    Default: 1
    Description: Provide the number of services for run your app
  VpcID:
    Type: "AWS::EC2::VPC::Id"
    Description: Select your VPC
  SubnetIDs:
    Type: "List<AWS::EC2::Subnet::Id>"
    Description: Select all the subnets where you want allocate your services
  DefSG:
    Type: "AWS::EC2::SecurityGroup::Id"
    Description: Select your default security group
  CodeBuildProjectName:
    Type: String
    Default: pipeline-build
    Description: Provide a name for the CodeBuild project
  CodeBuildImgCPU:
    Type: String
    Default: aws/codebuild/amazonlinux2-x86_64-standard:4.0
    Description: Provide a valid Image CPU for run the CodeBuild proceses, check the available values here https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html
  CodePipelineServiceRoleName:
    Type: String
    Default: AWSCodePipelineServiceRole
    Description: Provide a name for the ServiceRole needed for the CodePipeline

Resources:
  CodeCommit:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://hugo-manzoni-labs.s3.amazonaws.com/stacks/pipeline/codecommit.yml
      Parameters:
        RepoName: !Ref RepoName
        RepoBranchName: !Ref RepoBranchName
        SourceCodeBucket: !Ref SourceCodeBucket
        SourceFilePath: !Ref SourceFilePath
  ECR:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://hugo-manzoni-labs.s3.amazonaws.com/stacks/pipeline/ecr.yml
      Parameters:
        ECRRepoName: !Ref ECRRepoName
  ELBwithTGandSG:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://hugo-manzoni-labs.s3.amazonaws.com/stacks/pipeline/loadbalancer-tg-sg.yml
      Parameters:
        AppName: !Ref AppName
        VpcID: !Ref VpcID
        DefSG: !Ref DefSG
        SubnetIDs: !Join [",", !Ref SubnetIDs]
  ECSCluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://hugo-manzoni-labs.s3.amazonaws.com/stacks/pipeline/ecs-cluster.yml
      Parameters:
        NameCluster: !Ref NameCluster
  ECSTaskDefinition:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://hugo-manzoni-labs.s3.amazonaws.com/stacks/pipeline/ecs-taskdefinition.yml
      Parameters:
        ECSTaskDefName: !Ref ECSTaskDefName
        ECRRepoURL: !GetAtt ECR.Outputs.ECRRepoURL
        ECRRepoName: !GetAtt ECR.Outputs.ECRRepoName
  ECSService:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://hugo-manzoni-labs.s3.amazonaws.com/stacks/pipeline/ecs-service.yml
      Parameters:
        ECSServiceName: !Ref ECSServiceName
        ECSServiceDesiredCount: !Ref ECSServiceDesiredCount
        ECRRepoName: !GetAtt ECR.Outputs.ECRRepoName
        ECSClusterARN: !GetAtt ECSCluster.Outputs.ECSClusterARN
        ECSTaskDefinitionARN: !GetAtt ECSTaskDefinition.Outputs.ECSTaskDefinitionARN
        SecurityGroupIDs:
          !Join [",", [!Ref DefSG, !GetAtt ELBwithTGandSG.Outputs.SGOpenToAll]]
        VpcID: !Ref VpcID
        SubnetIDs: !Join [",", !Ref SubnetIDs]
        ARNTargetG: !GetAtt ELBwithTGandSG.Outputs.ARNTargetG
  CodeBuild:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://hugo-manzoni-labs.s3.amazonaws.com/stacks/pipeline/codebuild.yml
      Parameters:
        CodeBuildProjectName: !Ref CodeBuildProjectName
        CodeCommitRepoCloneHTTP: !GetAtt CodeCommit.Outputs.CodeCommitRepoCloneHTTP
        CodeCommitRepoARN: !GetAtt CodeCommit.Outputs.CodeCommitRepoARN
        ECRRepoName: !GetAtt ECR.Outputs.ECRRepoName
        CodeBuildImgCPU: !Ref CodeBuildImgCPU
        LogGroupName: !Ref CodeBuildProjectName
        LogStreamName: !Ref AppName
  CodePipeline:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://hugo-manzoni-labs.s3.amazonaws.com/stacks/pipeline/codepipeline.yml
      Parameters:
        AppName: !Ref AppName
        CodeCommitRepoName: !GetAtt CodeCommit.Outputs.CodeCommitRepoName
        CodeBuildNameProject: !GetAtt CodeBuild.Outputs.CodeBuildNameProject
        ECSClusterName: !GetAtt ECSCluster.Outputs.ECSClusterName
        ECSServiceName: !Ref ECSServiceName
        ArtifactStoreS3LocationName: !GetAtt CodeBuild.Outputs.S3Name
        CodePipelineServiceRoleName: !Ref CodePipelineServiceRoleName
        CodeCommitRepoBranchName: !Ref RepoBranchName
  EventBridgeRule:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://hugo-manzoni-labs.s3.amazonaws.com/stacks/pipeline/eventbridge-rule.yml
      Parameters:
        AppName: !Ref AppName
        PipelineARN:
          !Join [
            ":",
            [
              "arn:aws:codepipeline",
              !Ref AWS::Region,
              !Ref AWS::AccountId,
              !GetAtt CodePipeline.Outputs.AppPipelineName,
            ],
          ]
        CodeCommitRepoARN: !GetAtt CodeCommit.Outputs.CodeCommitRepoARN
  SSMParams:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://hugo-manzoni-labs.s3.amazonaws.com/stacks/pipeline/ssm-params.yml
      Parameters:
        CodeCommitRepoCloneHTTP: !GetAtt CodeCommit.Outputs.CodeCommitRepoCloneHTTP
        CodeCommitRepoCloneSSH: !GetAtt CodeCommit.Outputs.CodeCommitRepoCloneSSH
        AppUrl: !GetAtt ELBwithTGandSG.Outputs.ELBDNSName
