AWSTemplateFormatVersion: "2010-09-09"
Description: Save the URLs and useful parameters

Parameters:
  CodeCommitRepoCloneSSH:
    Default: Error
    Type: String
  CodeCommitRepoCloneHTTP:
    Default: Error
    Type: String
  AppUrl:
    Default: Error
    Type: String

Resources:
  SSMParamURLCloneSSH:
    Type: "AWS::SSM::Parameter"
    Description: "Url of the CodeCommit for clone the repo"
    Properties:
      Name: /Pipeline/CodeCommit/CloneSSH
      Type: String
      Value: !Ref CodeCommitRepoCloneSSH
  SSMParamURLCloneHTTP:
    Type: "AWS::SSM::Parameter"
    Description: "Url of the CodeCommit for clone the repo"
    Properties:
      Name: /Pipeline/CodeCommit/CloneHTTP
      Type: String
      Value: !Ref CodeCommitRepoCloneHTTP
  SSMParamAppURL:
    Type: "AWS::SSM::Parameter"
    Description: "Url of the Endpoint ELB for enter to the webapp"
    Properties:
      Name: /Pipeline/App/Url
      Type: String
      Value: !Ref AppUrl
