AWSTemplateFormatVersion: 2010-09-09
Description: Creation of load balancer with Security Group in 3 public Subnets
Parameters:
  VPC:
    Type: "AWS::EC2::VPC::Id"
    Description: Select your VPC
  SubnetPubA:
    Type: "AWS::EC2::Subnet::Id"
    Description: Select a Public Subnets
  SubnetPubB:
    Type: "AWS::EC2::Subnet::Id"
    Description: Select a Public Subnets
  SubnetPubC:
    Type: "AWS::EC2::Subnet::Id"
    Description: Select a Public Subnets
  MySecurityGroup:
    Type: "List<AWS::EC2::SecurityGroup::Id>"
    Description: Select the security group for your App
Resources:
  ELBV2ALB:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Type: application
      Scheme: internet-facing
      IpAddressType: ipv4
      SecurityGroups: !Ref MySecurityGroup
      SubnetMappings:
        - SubnetId: !Ref SubnetPubA
        - SubnetId: !Ref SubnetPubB
        - SubnetId: !Ref SubnetPubC
  HTTPlistener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref ELBV2TG
          Type: forward
      LoadBalancerArn: !Ref ELBV2ALB
      Port: 80
      Protocol: HTTP
  ELBV2TG:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      HealthCheckEnabled: true
      Port: 80
      Protocol: HTTP
      ProtocolVersion: HTTP1
      VpcId: !Ref VPC
  ALBStoreParamDNS:
    Type: "AWS::SSM::Parameter"
    Description: DNSName ALB for use in WP site
    Properties:
      Name: /App/WP/ALBDNSNAME
      Type: String
      Value: !GetAtt
        - ELBV2ALB
        - DNSName
