AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Creation of Auto Scaling Group associated with a Scaling Policy Request Count
  Target Value
Parameters:
  SubnetsPub:
    Type: "List<AWS::EC2::Subnet::Id>"
    Description: >-
      At least one public subnets Publics in different Availability Zones in the
      selected VPC
  VPC:
    Type: "AWS::EC2::VPC::Id"
    Description: A VPC that allows the load balancer access to the Internet
  LaunchTemplateId:
    Type: String
    Description: Launch Template information id example lt-018a79d6bdaa8c7fd
  LaunchTemplateVersion:
    Default: "1"
    Type: String
    Description: Launch Template information version
  TargetGroupLoadBalancerARN:
    Type: String
    Description: >-
      Target Group Load Balancer ARN example
      arn:partition:service:region:account-id:resource-type/resource-id
  ALBRequestCountTargetValue:
    Default: "50"
    Type: String
    Description: >-
      The optimal average request count per instance during any one-minute
      interval
  LoadBalancerFullName:
    Type: String
    Description: Load Balancer FullName example app/<load-balancer-name>/<load-balancer-id>
  TargetGroupFullName:
    Type: String
    Description: >-
      Targe tGroup FullName example
      targetgroup/<target-group-name>/<target-group-id>
Resources:
  myASG:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateId
        Version: !Ref LaunchTemplateVersion
      TargetGroupARNs:
        - !Ref TargetGroupLoadBalancerARN
      VPCZoneIdentifier: !Ref SubnetsPub
      HealthCheckType: ELB
      DesiredCapacity: "1"
      MinSize: "1"
      MaxSize: "3"
      Tags:
        - Key: Name
          PropagateAtLaunch: true
          Value: Wordpress-ASG
  myALBRequestCountPolicy:
    Type: "AWS::AutoScaling::ScalingPolicy"
    Properties:
      AutoScalingGroupName: !Ref myASG
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ALBRequestCountPerTarget
          ResourceLabel: !Join
            - /
            - - !Ref LoadBalancerFullName
              - !Ref TargetGroupFullName
        TargetValue: !Ref ALBRequestCountTargetValue
