AWSTemplateFormatVersion: 2010-09-09
Description: Creation of EFS File System with 3 Mount targets
Parameters:
  SubnetAppA:
    Type: "AWS::EC2::Subnet::Id"
    Description: Select a Subnets for mount the target in that AZ
  SubnetAppB:
    Type: "AWS::EC2::Subnet::Id"
    Description: Select a Subnets for mount the target in that AZ
  SubnetAppC:
    Type: "AWS::EC2::Subnet::Id"
    Description: Select a Subnets for mount the target in that AZ
  SGMountTarget:
    Type: "List<AWS::EC2::SecurityGroup::Id>"
    Description: Security Group for EFS Mount Target
Resources:
  FileSystemResource:
    Type: "AWS::EFS::FileSystem"
    Properties:
      BackupPolicy:
        Status: ENABLED
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS
        - TransitionToPrimaryStorageClass: AFTER_1_ACCESS
      PerformanceMode: generalPurpose
      ThroughputMode: bursting
      Encrypted: false
  MountTargetA:
    Type: "AWS::EFS::MountTarget"
    Properties:
      FileSystemId: !Ref FileSystemResource
      SubnetId: !Ref SubnetAppA
      SecurityGroups: !Ref SGMountTarget
  MountTargetB:
    Type: "AWS::EFS::MountTarget"
    Properties:
      FileSystemId: !Ref FileSystemResource
      SubnetId: !Ref SubnetAppB
      SecurityGroups: !Ref SGMountTarget
  MountTargetC:
    Type: "AWS::EFS::MountTarget"
    Properties:
      FileSystemId: !Ref FileSystemResource
      SubnetId: !Ref SubnetAppC
      SecurityGroups: !Ref SGMountTarget
  StoreParamEFS:
    Type: "AWS::SSM::Parameter"
    Description: ID FileSystem for use in WP site
    Properties:
      Name: /App/WP/EFSFSID
      Type: String
      Value: !Ref FileSystemResource
