Description: Registration of a valid Email on AWS SES
Parameters:
  Email:
    Description: This email will be register on SES for recive the emails from the app.
    Type: String
    AllowedPattern: '/[^\s@]+@[^\s@]+\.[^\s@]+/'
    ConstraintDescription: You should enter a valid email
Resources:
  EmailIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: !Ref Email
